[toolchain]
solana_version = "1.18.26"

[features]
seeds = true
skip-lint = false

[programs.localnet]
tradeit_escrow = "Es7dux19AYKphx5PtTn7vsem96pqTBKc6oQp9gosfERi"

[programs.devnet]
tradeit_escrow = "Es7dux19AYKphx5PtTn7vsem96pqTBKc6oQp9gosfERi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-node tests/tradeit-escrow.ts"
